### ISSUE TITLE
There was an error in evaluating the Pre-request Script:  Error: init failed:unsupported PKCS#1/5 hexadecimal key

### ISSUE THREAD

**Issue by jwomack** [movinalot/intersight-rest-api#2]
I'm trying to use the imported postman collection "GET Compute / PhysicalSummaries" .
After I send the request, I get:

> There was an error in evaluating the Pre-request Script:  Error: init failed:unsupported PKCS#1/5 hexadecimal key

The postman console shows:
jsrasign library not already downloaded. Downloading now. 
Resolved Request:
computedDigest:
SHA-256= <rest of digest>
Query String:
Error:

Here is the request right before the error:
`(request-target): get /api/v1/compute/physicalsummaries
date: Fri, 24 Apr 2020 18:30:17 GMT
digest: SHA-256=<rest of digest>
host: intersight.com`

**Comment by jwomack** [comment]
OS:  Windows 10

Postman for Windows
Version 7.22.1
win32 10.0.17763 / x64

**Comment by movinalot** [comment]
@jwomack 

I'm not able to recreate this error.  I'm wondering if your key is the issue.

Did you follow the lab Introduction to the "Cisco Intersight REST API" in this group of labs 

https://developer.cisco.com/learning/modules/intersight-rest-api

**Comment by jwomack** [comment]
Yes, I was following along in the lab.  I think this issue is related to a bad API key.  I recreated the API key in a different account and it is working.  Not sure why, but this issue can be closed.

**Comment by smarsou** [comment]
I had exactly the same issue.

However, using the key "_API key for OpenAPI schema version 2 (deprecated)_" instead of the version 3 worked for me...
